services:
  postgres:
    image: postgres
    container_name: postgres-stoom-store
    ports:
      - "5432:5432"
    networks:
      - stoom-store-network
    environment:
      POSTGRES_USER: stoom-store
      POSTGRES_PASSWORD: stoom-store
      POSTGRES_DB: store
  stoom-store:
    container_name: stoom-store
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - stoom-store-network
networks:
  stoom-store-network:
    name: stoom-store-network
    driver: bridge