server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: stoom-store
    password: stoom-store

  jpa:
    hibernate:
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect